### ISSUE TITLE
Code implementation

### ISSUE THREAD

**Issue by itsnamgyu** [asrafulashiq/dynamic-cdfsl#1]
Thank you for your work on CD-FSL. We're interested in citing your paper as a baseline comparison for our work, but we would like to test the Dynamic Distillation method on more settings. Do you have any plans on releasing the code anytime soon? Thanks.

**Comment by asrafulashiq** [comment]
Thanks for your interest. We plan to release the code in a couple of weeks. In the meantime, if you need the codes as soon as possible, send me an email, I can share the untested version.

**Comment by nuistji** [comment]
Excellent work! It supplies a new direction for cross-domain few-shot learning. Can you please release your code? It will be very help. Thanks!
