### ISSUE TITLE
tieredImageNet pre-trained model

### ISSUE THREAD

**Issue by itsnamgyu** [asrafulashiq/dynamic-cdfsl#5]
Would it be possible for you to provide the pre-trained checkpoint for ResNet18 trained on tieredImageNet (step 1 pre-training)? Thanks.

**Comment by asrafulashiq** [comment]
Sure. Here it is: https://drive.google.com/drive/folders/1jku_EzTHMHMCw_3qwmolzk3jdA3TpbVo?usp=sharing

Thanks!

**Comment by itsnamgyu** [comment]
Much appreciated!
