### ISSUE TITLE
About requirement.txt

### ISSUE THREAD

**Issue by wxxhahaha** [asrafulashiq/dynamic-cdfsl#8]
Hello,I failed thousand times to install the Hydra==2.5 in the requirement.txt
Is the Hydra==2.5 important?Or hydra-core=1.1.0 dev4 is enough for the experiment.
Hope for your reply!

**Comment by asrafulashiq** [comment]
Hi, I don't think Hydra is necessary. You should be able to run with hydra-core.

**Comment by wxxhahaha** [comment]
Thanks a lot!!!!
